---
- name: precheck
  hosts: bastion 
  gather_facts: false

  tasks:
  - name: use in a loop
    debug: msg="Check that all of our A records exist {{ item }}"
    with_items: "{{ lookup('dig', '{{ item }}./MX', wantlist=True) }}"

- debug: msg="XMPP service for gmail.com. is available at {{ item.target }} on port {{ item.port }}"
  with_items: "{{ lookup('dig', '_xmpp-server._tcp.gmail.com./SRV', 'flat=0', wantlist=True) }}"


