---
- name: Prepare lb node
  hosts: proxies 
  gather_facts: false

  tasks:
  - name: Install haproxy
    package:
      name: haproxy
      state: latest
    tags:
      - server

  - name: Create config from template
    template:
      src: templates/haproxy.conf.j2
      dest: /etc/haproxy/haproxy.conf

  - name: Open Firewall ports 
    become: true
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    register: firewall_http
    loop:
      - "80/tcp"
      - "6443/tcp"
      - "443/tcp"
      - "22623/tcp"

  - name: Restart the Firewall service
    become: true
    service:
      name: firewalld
      state: restarted
    when: firewall_http.changed

  - name: Set selinux requirements
    become: true
    seboolean:
      name: haproxy_connect_any
      state: true
      persistent: true

  - name: Start and enable haproxy services
    systemd:
        name: "haproxy"
        state: started
        enabled: yes
    tags:
      - server

